version: 2.1

orbs:
  ci: bigcommerce/internal@volatile
  node: bigcommerce/internal-node@volatile

jobs:
  build:
    executor:
      name: node/node
      node-version: "10"
    steps:
      - ci/pre-setup
      - ci/merge-base
      - node/yarn-install
      - run:
          name: 'Test'
          command: 'yarn run test'
      - run:
          name: 'Validate Commits @circle'
          command: '[ -z "$MERGE_BASE_SHA1" ] || node ./bin/validate-commits.js ${MERGE_BASE_SHA1}..${CIRCLE_SHA1}'
      - run:
          name: 'Validate Commits @master'
          command: '[ -z "$MERGE_BASE_SHA1" ] || npx @bigcommerce/validate-commits ${MERGE_BASE_SHA1}..${CIRCLE_SHA1}'
